// Copyright (c) 2026 Glavo
// SPDX-License-Identifier: MPL-2.0

package org.glavo.ruyi.imager.gradle;

import org.jetbrains.annotations.NotNullByDefault;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;

/// Provides helpers for Gradle task output directories generated by buildSrc tasks.
@NotNullByDefault
final class GeneratedDirectories {
    /// Creates a generated directory helper namespace.
    private GeneratedDirectories() {
    }

    /// Deletes a directory tree when it exists, then recreates the directory.
    ///
    /// @param directory generated output directory.
    /// @throws IOException if the directory cannot be deleted or created.
    static void recreateDirectory(Path directory) throws IOException {
        deleteExisting(directory);
        Files.createDirectories(directory);
    }

    /// Deletes a generated directory tree when it exists.
    ///
    /// @param directory generated output directory.
    /// @throws IOException if the directory cannot be deleted.
    static void deleteExisting(Path directory) throws IOException {
        deleteRecursively(directory);
    }

    /// Deletes a directory tree without following symbolic links.
    ///
    /// @param directory directory to delete.
    /// @throws IOException if any path cannot be deleted.
    private static void deleteRecursively(Path directory) throws IOException {
        if (!Files.exists(directory, LinkOption.NOFOLLOW_LINKS)) {
            return;
        }

        List<Path> paths;
        try (Stream<Path> stream = Files.walk(directory)) {
            paths = stream
                    .sorted(Comparator.reverseOrder())
                    .toList();
        }

        for (Path path : paths) {
            Files.delete(path);
        }
    }
}
